/*
 * Copyright 2018 Tallence AG
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tallence.formeditor.cae.handler;

import com.coremedia.blueprint.common.contentbeans.CMNavigation;
import org.springframework.util.MultiValueMap;

/**
 * Encapsulates requests to a captcha service.
 */
public interface CaptchaService {

  /**
   * Resolves the website-secret for the captcha for the given Context.
   *
   * The context is currently ignored. Use it if you need multiple secrets for your sites.
   */
  String getWebsiteSecretForSite(CMNavigation currentContext);


  /**
   * Asks the Captcha Service, if the given response is valid.
   * @param postData contains the captcha token, generated by the frontend widget
   * @return true, if the captcha service validates the request, false otherwise.
   */
  boolean isHuman(MultiValueMap<String, String> postData, CMNavigation currentContext);

}
