/*
 * Copyright 2018 Tallence AG
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.tallence.formeditor.cae.handler;

import com.coremedia.blueprint.common.contentbeans.CMNavigation;

/**
 * Encapsulates requests to google reCaptcha.
 * The impl from CoreMedia elastic social Extension might be used.
 */
public interface ReCaptchaService {

  /**
   * Resolves the website-secret for google reCaptcha for the given Context.
   *
   * The context is currently ignored. Use it if you need multiple secrets for your sites.
   */
  String getWebsiteSecretForSite(CMNavigation currentContext);


  /**
   * Asks the Google Recaptcha Service, if the given googleReCaptchaResponse is valid.
   * @param googleReCaptchaResponse token, generated by the reCaptcha widget, by using the public key
   * @return true, if the google reCaptcha service validates the request, false otherwise.
   */
  boolean isHuman(String googleReCaptchaResponse, CMNavigation currentContext);

}
