import ResourceBundleUtil from "@jangaroo/runtime/l10n/ResourceBundleUtil";
import FormEditor_properties from "./FormEditor_properties";

/**
 * Overrides of ResourceBundle "FormEditor" for Locale "de".
 * @see FormEditor_properties#INSTANCE
 */
ResourceBundleUtil.override(FormEditor_properties, {
  FormEditor_label_possible_elements: "Auswahl Formularelemente",
  FormEditor_title_group_input: "Eingabefelder",
  FormEditor_title_group_multiple: "Mehrfachauswahl",
  FormEditor_title_group_other: "Weitere Elemente",
  FormEditor_label_element_textField: "Textfeld",
  FormEditor_label_element_numberField: "Numerisches Feld",
  FormEditor_label_element_textOnly: "Hinweistext",
  FormEditor_label_element_textArea: "Text-Area",
  FormEditor_label_element_fileUpload: "Datei Upload",
  FormEditor_label_element_radioButtons: "Radio-Buttons",
  FormEditor_label_element_checkBoxes: "Check-Boxes",
  FormEditor_label_element_selectBox: "Select-Box",
  FormEditor_label_element_usersMail: "Nutzer-E-Mail",
  FormEditor_label_element_dateField: "Datumsfeld",
  FormEditor_label_element_consentFormCheckBox: "Einverständnis",
  FormEditor_label_element_faxField: "Fax",
  FormEditor_label_element_phoneField: "Telefon",
  FormEditor_label_element_streetNumberField: "Straße & Haus-Nr.",
  FormEditor_label_element_zipField: "Postleitzahl",
  FormEditor_label_query_title: "Gewählte Formularelemente",
  FormEditor_tooltip_deletethis: "Dieses Formularelement löschen",
  FormEditor_label_delete_all_elements: "Alle Elemente löschen",
  FormEditor_delete_elements_title: "Alle Formularelemente löschen",
  FormEditor_delete_elements_msg: "Möchten Sie wirklich alle Formularelemente löschen?",
  FormEditor_text_add_element: "Ziehen Sie ein Formularelement hierher.",
  FormEditor_text_label_option: "Optionen",
  FormEditor_text_add_option: "Neue Option hinzufügen",
  FormEditor_text_add_option_disabled: "Der Optionstext darf nicht leer sein und keine Punkte enthalten.",
  FormEditor_text_edit_option: "Option bearbeiten",
  FormEditor_text_save_option: "Option löschen",
  FormEditor_text_move_option_up: "Option nach oben",
  FormEditor_text_move_option_down: "Option nach unten",
  FormEditor_elements_target_title: "Gewählte Elemente",
  FormEditor_label_show_help: "Hilfe",
  FormEditor_help_title: "Hilfe zu den Formular-Elementen",
  FormEditor_window_html_content_key: "formEditor-help-de",
  FormEditor_actions_default: "Daten in Datenbank speichern",
  FormEditor_actions_mail: "Daten per Mail versenden",
  FormEditor_usersMail_mailType_label: "Mail-Versand",
  FormEditor_usersMail_mailType_checkbox: "User entscheidet selbst per CheckBox",
  FormEditor_usersMail_mailType_always: "User-Mail immer senden",
  FormEditor_usersMail_mailType_never: "User-Mail nie senden",
  FormEditor_tab_content_title: "Inhalt",
  FormEditor_tab_formData_title: "Formular Konfiguration",
  FormEditor_tab_formFields_title: "Formularfelder",
  FormEditor_formAction_default_title: "Mail versenden",
  FormEditor_element_group_labelField_text: "Anzeigename",
  FormEditor_element_group_labelField_emptyText: "Dieser Wert wird im Formular angezeigt. Erforderlich.",
  FormEditor_element_group_valueField_text: "Options-Wert",
  FormEditor_element_group_valueField_emptyText: "Dieser Wert wird beim Senden des Formulares übertragen.",
  FormEditor_element_group_valueField_hint: "Füllen Sie dieses Feld nur aus, wenn der Options-Wert abweichend vom Anzeigenamen sein soll.",
  FormEditor_element_collapsiblePanel_label: "Einklappbares Formularelement.",
  FormEditor_element_textField_emptyText: "Bitte einen Text eingeben.",
  FormEditor_element_numberField_emptyText: "Bitte eine Nummer eingeben.",
  FormEditor_element_hiddenField_value_label: "Versteckter Wert",
  FormEditor_element_hiddenField_value_emptyText: "Bitte den versteckten Wert eingeben.",
  FormEditor_element_name_label: "Name",
  FormEditor_element_name_emptyText: "Der Name des Feldes.",
  FormEditor_element_hint_label: "Hinweis",
  FormEditor_element_hint_emptyText: "Wird neben dem Formularfeld angezeigt.",
  FormEditor_element_placeholder_label: "Platzhalter",
  FormEditor_element_placeholder_emptyText: "Wird als Platzhalter in dem Formularfeld angezeigt.",
  FormEditor_element_regexp_label: "Regexp-Validator",
  FormEditor_element_regexp_emptyText: "Der Regexp-Validator, z.B.: [a-b]+",
  FormEditor_element_mandatory_label: "Pflichtfeld",
  FormEditor_element_linkTarget_label: "Einverständniserklärung",
  FormEditor_element_hint_linkTarget_label: "Mit dem Platzhalter %link% kann die Einverständniserklärung verlinkt werden",
  FormEditor_element_max_size_file_label: "Maximale Dateigröße (in KB)",
  FormEditor_element_max_size_file_emptyText: "Hier die maximale Dateigröße (in KB) eingeben.",
  FormEditor_element_group_default_tooltip: "Diese Option per Default auswählen.",
  FormEditor_fields_textArea_rows_label: "Zeilen",
  FormEditor_fields_textArea_rows_text: "Wieviele Zeilen sollen in der Textarea angezeigt werden.",
  FormEditor_validator_maxSize_label: "Max. Zeichen",
  FormEditor_validator_maxSize_text: "Der Wert des Feldes darf höchstens so lang sein.",
  FormEditor_validator_minSize_label: "Min. Zeichen",
  FormEditor_validator_minSize_text: "Der Wert des Feldes muss mindestens so lang sein.",
  FormEditor_validator_maxValue_label: "Max. Wert",
  FormEditor_validator_maxValue_text: "Der Wert des Feldes darf höchstens so groß sein.",
  FormEditor_validator_minValue_label: "Min. Wert",
  FormEditor_validator_minValue_text: "Der Wert des Feldes muss mindestens so groß sein.",
  FormEditor_validator_minDate_label: "Min. Datum",
  FormEditor_validator_minDateToday_text: "Nutze immer das aktuelle Datum als min. Datum.",
  FormEditor_validator_maxDate_label: "Max. Datum",
  FormEditor_validator_maxDateToday_text: "Nutze immer das aktuelle Datum als max. Datum.",
  FormEditor_validator_checkboxes_minSize_label: "Min. Auswahl",
  FormEditor_validator_checkboxes_minSize_text: "Mindestanzahl von Checkboxen, die gleichzeitig ausgewählt werden dürfen.",
  FormEditor_validator_checkboxes_maxSize_label: "Max. Auswahl",
  FormEditor_validator_checkboxes_maxSize_text: "Maximalanzahl von Checkboxen, die gleichzeitig ausgewählt werden dürfen.",
  FormEditor_advancedSettings_title: "Erweiterte Einstellungen",
  FormEditor_advancedSettings_tabs_visibility_title: "Sichtbarkeit",
  FormEditor_advancedSettings_tabs_visibility_active_fieldLabel: "Aktiv",
  FormEditor_advancedSettings_tabs_visibility_element_fieldLabel: "Abhängig von",
  FormEditor_advancedSettings_tabs_visibility_value_fieldLabel: "Wert",
  FormEditor_advancedSettings_tabs_visibility_description: "Mit dieser Einstellung kann die Sichtbarkeit gesteuert werden. Wenn die Option aktiv ist, kann ein Formular element ausgewählt werden. Anschließend kann ein Wert eingegeben werden von dem die Sichtbarkeit des Feldes abhängt.",
  FormEditor_advancedSettings_tabs_id_title: "IDs",
  FormEditor_advancedSettings_tabs_id_fieldLabel: "Benutzerdefinierte ID",
  FormEditor_advancedSettings_tabs_id_emptyText: "Hier eine benutzerdefinierte ID eingeben.",
  FormEditor_advancedSettings_tabs_id_description: "In diesem Tab kann eine benutzer definierte ID eingegeben werden, mit der das Formularelement referenziert werden kann.",
  FormEditor_advancedSettings_tabs_layout_title: "Layout",
  FormEditor_advancedSettings_tabs_layout_columnWidth_fieldLabel: "Spaltenbreite",
  FormEditor_advancedSettings_tabs_layout_columnWidth_emptyText: "Hier eine Spaltenbreite für das Formularfeld eingeben.",
  FormEditor_advancedSettings_tabs_layout_breakAfter_fieldLabel: "Zeilenumbruch nach diesem Element.",
  FormEditor_advancedSettings_tabs_layout_description: "Mit dieser Einstellung kann eine eigene Spaltenbreite für das Feld vergeben werden.",
  FormEditor_pages_mode_single: "Mehrseiten-Modus deaktivieren",
  FormEditor_pages_mode_multi: "Mehrseiten-Modus aktivieren",
  FormEditor_pages_mode_switch_title: "Seitenmodus",
  FormEditor_pages_mode_switch_text_multi: "Den Mehrseiten-Modus aktivieren und alle Elemente in die erste Seite verschieben.",
  FormEditor_pages_mode_switch_text_single: "Den Einseiten-Modus aktivieren und alle Elemente in diese Seite verschieben.",
  FormEditor_pages_default_title: "Default",
  FormEditor_pages_new_title: "Neue Seite",
  FormEditor_pages_properties_title: "Seiten Eigenschaften",
  FormEditor_page_type_field_label: "Seiten Typ",
  FormEditor_page_type_empty_text: "Seitentyp auswählen",
  FormEditor_page_type_default_label: "Default",
  FormEditor_page_type_summary_label: "Zusammenfassung",
  FormEditor_page_title_field_label: "Seiten Titel",
  FormEditor_page_title_empty_text: "Seitentitel eingeben",
  FormEditor_page_tab_moveUp_text: "Die Seite nach links verschieben",
  FormEditor_page_tab_moveDown_text: "Die Seite nach rechts verschieben",
  FormEditor_page_tab_delete_text: "Die Seite löschen",
  FormEditor_page_tab_insertBefore_text: "Links eine neue Seite einfügen",
  FormEditor_page_tab_insertAfter_text: "Rechts eine neue Seite einfügen",
});
